version: '3.7'

services:
  api:
    container_name: boilerplate-api
    command: yarn dev:server
    build: .
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@database:5432/${DB_NAME}?connect_timeout=300
    volumes:
      - .:/usr/app
    networks:
      - boilerplate-network
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: boilerplate-database
    image: postgres:14.1-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - boilerplate-volume:/data/postgres
    env_file:
      - .env
    networks:
      - boilerplate-network

volumes:
  boilerplate-volume:
    driver: local

networks:
  boilerplate-network:
    driver: bridge
