version: '3.7'

services:
  api:
    container_name: boilerplate-api
    command: yarn dev:server
    build: .
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=boilerplate-database
    volumes:
      - .:/usr/app
    networks:
      - boilerplate-network
    depends_on:
      - database

  database:
    container_name: boilerplate-database
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - boilerplate-volume:/data/postgres
    networks:
      - boilerplate-network

volumes:
  boilerplate-volume:
    driver: local

networks:
  boilerplate-network:
    driver: bridge
